{
 "title": "assignment3",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Top 3 Busiest Sensors  (Leaderboard)",
   "type": "table",
   "description": "This selects the top 3 sensors with the highest total vehicle count over the past 30 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(3, sum by (sensor_id) (sum_over_time(busiest_sensor[30m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Congestion Hotspots",
   "type": "heatmap",
   "description": "This aggregates the count of \"HIGH\" congestion events per sensor over 5‑minute windows.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (sensor_id) (sum_over_time(congestion_hotspot[5m]))\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Speed per Sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "avg by (sensor_id) (avg_over_time(avg_speed[10m]))\n\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Traffic Volume Over Time",
   "type": "barchart",
   "description": "This sums the values of total_vehicle_count over each 5‑minute window for each sensor. The outer sum by (sensor_id) groups the results by sensor.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (sensor_id) (sum_over_time(total_vehicle_count[5m]))\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}