# version: "3.8"

# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#     ports:
#       - "2181:2181"

#   kafka:
#     image: confluentinc/cp-kafka:latest
#     ports:
#       - "9092:9092"
#       - "7075:7075" # JMX Exporter port
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_JMX_PORT: 7075
#       KAFKA_JMX_OPTS: >-
#         -Dcom.sun.management.jmxremote
#         -Dcom.sun.management.jmxremote.local.only=false
#         -Dcom.sun.management.jmxremote.authenticate=false
#         -Dcom.sun.management.jmxremote.ssl=false
#         -Dcom.sun.management.jmxremote.port=7071
#         -Dcom.sun.management.jmxremote.rmi.port=7071
#         -Djava.rmi.server.hostname=localhost
#         -javaagent:/usr/app/jmx_prometheus_javaagent-0.20.0.jar=7071:/usr/app/jmx-exporter-config.yaml
#     volumes:
#       - ./jmx-exporter-config.yaml:/usr/app/jmx-exporter-config.yaml
#       - ./jmx_prometheus_javaagent-0.20.0.jar:/usr/app/jmx_prometheus_javaagent-0.20.0.jar
#     depends_on:
#       - zookeeper

#   prometheus:
#     image: prom/prometheus
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml

#   grafana:
#     image: grafana/grafana
#     ports:
#       - "3000:3000"

version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092" # Kafka broker
      - "9999:9999" # Kafka JMX port (for RMI)
      - "8080:8080" # Prometheus JMX Exporter HTTP port
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_OPTS: >-
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.port=9999
        -Dcom.sun.management.jmxremote.rmi.port=9999
        -Djava.rmi.server.hostname=localhost
        -javaagent:/usr/app/jmx_prometheus_javaagent-0.20.0.jar=8080:/usr/app/jmx-exporter-config.yaml
    volumes:
      - ./jmx_prometheus_javaagent-0.20.0.jar:/usr/app/jmx_prometheus_javaagent-0.20.0.jar
      - ./jmx-exporter-config.yaml:/usr/app/jmx-exporter-config.yaml
    depends_on:
      - zookeeper

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
